export const GET_POKEMONS = "GET_POKEMONS";
export const POKE_DETAIL = "POKE_DETAIL";
export const CLEAN_DETAIL = "CLEAN_DETAIL";
export const FILTER_BY_TYPE = "FILTER_BY_TYPE"
export const FILTER_CREATED = "FILTER_CREATED"
export const ORDER_BY_NAME = "ORDER_BY_NAME"
export const ORDER_BY_ATTACK = 'ORDER_BY_ATTACK'
export const RESET_POKEMONS = 'RESET_POKEMONS'
export const GET_TYPES = 'GET_TYPES'
export const GET_NAME_POKEMONS = 'GET_NAME_POKEMONS'; 
export const POST_POKEMON ="POST_POKEMON";
export const SET_ERROR = "SET_ERROR";

